// <auto-generated />
using BoardGamesManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoardGamesManager.Migrations
{
    [DbContext(typeof(BoardGamesManagerContext))]
    [Migration("20210209105703_AddedBoardGamesListModel2")]
    partial class AddedBoardGamesListModel2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BoardGameDataBaseModelHuy", b =>
                {
                    b.Property<int>("BoardGamesListId")
                        .HasColumnType("int");

                    b.Property<int>("BoardGamesListId1")
                        .HasColumnType("int");

                    b.HasKey("BoardGamesListId", "BoardGamesListId1");

                    b.HasIndex("BoardGamesListId1");

                    b.ToTable("BoardGameDataBaseModelHuy");
                });

            modelBuilder.Entity("BoardGamesManager.Models.BoardGameDataBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkToStore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfPlayers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RecomendedAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoardGame");
                });

            modelBuilder.Entity("BoardGamesManager.Models.Huy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Huys");
                });

            modelBuilder.Entity("BoardGameDataBaseModelHuy", b =>
                {
                    b.HasOne("BoardGamesManager.Models.BoardGameDataBaseModel", null)
                        .WithMany()
                        .HasForeignKey("BoardGamesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGamesManager.Models.Huy", null)
                        .WithMany()
                        .HasForeignKey("BoardGamesListId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
